apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mernk8s.azurecr.io/mern-backend:v1
          ports:
            - containerPort: 5050
          env:
            
            - name: MONGO_URI
              value: mongodb://mongodb:27017/mydatabase
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 5050
      targetPort: 5050
