apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mernk8s.azurecr.io/mern-frontend:v1
          ports:
            - containerPort: 5173
          env:
           
            - name: REACT_APP_API_URL
              value: http://backend-service:5050
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 5173
      targetPort: 5173
